---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minimal-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "minimal-app.labels" . | nindent 4 }}
  {{- range $key, $val := .Values.labels }}
  {{- $key | nindent 4 }}: {{ $val | quote }}
  {{- end}}
spec:
  type: ClusterIP
  selector:
  {{- include "minimal-app.selectorLabels" . | nindent 4 }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  type: ClusterIP
