{{- if and .Values.deployer .Values.deployer.saReadWriteRoleARN }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "minimal-app.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.deployer.saReadWriteRoleARN }}
{{- end }}
